version: '3.1'

services:

  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=pgdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432
    networks:
      - chatroom
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  app:
    build:
      context: ./
      dockerfile: docker/app.docker
    working_dir: /var/www
    volumes:
      - .:/var/www:delegated
      - node_modules:/var/www/node_modules:delegated
    ports:
      - 9130:9130
      - 9131:9131
    networks:
      - chatroom
    depends_on:
      - db
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  web:
    build:
      context: ./
      dockerfile: docker/web.docker
    volumes:
      - .:/var/www:delegated
    ports:
      - 9100:80
    networks:
      - chatroom
    depends_on:
      - app
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

networks:
  chatroom:
    driver: bridge

volumes:
  db_data:
  node_modules:
